language: node_js
node_js:
  - "0.10" # latest stable release
  - "0.11" # latest development release, may be unstable
before_install: npm install -g grunt-cli
install: npm install
matrix:
  fast_finish: true
  allow_failures:
  - node_js: "0.11"